# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Relocate runtime mesh opinions into instanceable geometry prototypes."""

from __future__ import annotations

import os

from pxr import Sdf
from simready.asset_transformer import RuleConfigurationParam, RuleInterface

from .. import utils


class RuntimeInstanceRoutingRule(RuleInterface):
    """Build runtime-specific instance layers and swap them from enabled payloads.

    Geometry routing replaces source meshes with instanceable references. USD
    intentionally ignores local opinions on descendants of instances, so the
    original solver layers can no longer affect the actual mesh. This rule
    copies the base instances layer per runtime, relocates solver opinions onto
    the prototype mesh, and rewrites each enabled layer to explicitly reference
    the matching runtime prototype.
    """

    def get_configuration_parameters(self) -> list[RuleConfigurationParam]:
        return [
            RuleConfigurationParam(
                name="instances_layer",
                display_name="Base Instances Layer",
                param_type=str,
                description="Instances layer generated by GeometriesRoutingRule.",
                default_value="payloads/instances.usda",
            ),
            RuleConfigurationParam(
                name="runtimes",
                display_name="Runtime Layers",
                param_type=list,
                description="Runtime folder and generated instance-layer definitions.",
                default_value=[
                    {"folder": "PhysX", "instances_layer": "payloads/instances_physx.usda"},
                    {"folder": "Newton", "instances_layer": "payloads/instances_newton.usda"},
                    {"folder": "MuJoCo", "instances_layer": "payloads/instances_mujoco.usda"},
                ],
            ),
        ]

    @staticmethod
    def _walk_prim_specs(prim_spec: Sdf.PrimSpec):
        yield prim_spec
        for child in prim_spec.nameChildren.values():
            yield from RuntimeInstanceRoutingRule._walk_prim_specs(child)

    @staticmethod
    def _reference_map(base_layer: Sdf.Layer, instances_filename: str) -> dict[Sdf.Path, Sdf.Path]:
        mapping: dict[Sdf.Path, Sdf.Path] = {}
        for root_prim in base_layer.rootPrims:
            for prim_spec in RuntimeInstanceRoutingRule._walk_prim_specs(root_prim):
                references = prim_spec.referenceList.GetAddedOrExplicitItems()
                for reference in references:
                    if os.path.basename(reference.assetPath) != instances_filename:
                        continue
                    if reference.primPath:
                        mapping[prim_spec.path] = reference.primPath
                        break
        return mapping

    @staticmethod
    def _has_runtime_mesh_opinions(prim_spec: Sdf.PrimSpec) -> bool:
        if prim_spec.HasInfo("apiSchemas"):
            schemas = prim_spec.GetInfo("apiSchemas").GetAddedOrExplicitItems()
            if any(schema.startswith(("Physx", "Newton", "Mjc", "PhysicsMeshCollisionAPI")) for schema in schemas):
                return True
        return any(
            attribute.name == "physics:approximation" or attribute.name.startswith(("physx", "newton:", "mjc:"))
            for attribute in prim_spec.attributes
        )

    @staticmethod
    def _find_source_root(path: Sdf.Path, mappings: dict[Sdf.Path, Sdf.Path]) -> Sdf.Path | None:
        candidates = [source_root for source_root in mappings if path.HasPrefix(source_root)]
        return max(candidates, key=lambda candidate: len(candidate.pathString)) if candidates else None

    @staticmethod
    def _prototype_mesh_path(source_path: Sdf.Path, source_root: Sdf.Path, prototype_root: Sdf.Path) -> Sdf.Path:
        if source_path == source_root:
            return prototype_root.AppendChild(source_path.name)
        return prototype_root.AppendPath(source_path.MakeRelativePath(source_root))

    @staticmethod
    def _merge_prim_opinions(
        source_layer: Sdf.Layer,
        source_spec: Sdf.PrimSpec,
        destination_layer: Sdf.Layer,
        destination_path: Sdf.Path,
    ) -> None:
        destination_spec = destination_layer.GetPrimAtPath(destination_path)
        if destination_spec is None:
            destination_spec = utils.create_prim_spec(
                destination_layer,
                destination_path.pathString,
                specifier=Sdf.SpecifierOver,
            )
        if destination_spec is None:
            raise RuntimeError(f"Could not create runtime prototype prim {destination_path}")

        if source_spec.HasInfo("apiSchemas"):
            source_schemas = source_spec.GetInfo("apiSchemas").GetAddedOrExplicitItems()
            existing_schemas = (
                destination_spec.GetInfo("apiSchemas").GetAddedOrExplicitItems()
                if destination_spec.HasInfo("apiSchemas")
                else []
            )
            combined = list(dict.fromkeys([*existing_schemas, *source_schemas]))
            destination_spec.SetInfo("apiSchemas", Sdf.TokenListOp.Create(prependedItems=combined))

        for property_spec in source_spec.properties:
            destination_property_path = destination_path.AppendProperty(property_spec.name)
            Sdf.CopySpec(source_layer, property_spec.path, destination_layer, destination_property_path)

    @staticmethod
    def _remove_prim_spec(layer: Sdf.Layer, path: Sdf.Path) -> None:
        parent_spec = layer.GetPrimAtPath(path.GetParentPath())
        if parent_spec is not None and path.name in parent_spec.nameChildren:
            del parent_spec.nameChildren[path.name]

    @staticmethod
    def _author_runtime_reference(
        enabled_layer: Sdf.Layer,
        source_root: Sdf.Path,
        runtime_instances_path: str,
        prototype_root: Sdf.Path,
    ) -> None:
        source_spec = enabled_layer.GetPrimAtPath(source_root)
        if source_spec is None:
            source_spec = utils.create_prim_spec(
                enabled_layer,
                source_root.pathString,
                specifier=Sdf.SpecifierOver,
            )
        if source_spec is None:
            raise RuntimeError(f"Could not author runtime reference at {source_root}")

        for property_name in [prop.name for prop in source_spec.properties]:
            del source_spec.properties[property_name]
        for child_name in list(source_spec.nameChildren.keys()):
            del source_spec.nameChildren[child_name]
        if source_spec.HasInfo("apiSchemas"):
            source_spec.ClearInfo("apiSchemas")
        utils.clear_composition_arcs(source_spec, make_explicit=True)

        relative_path = utils.get_relative_layer_path(enabled_layer, runtime_instances_path)
        source_spec.referenceList.explicitItems = [Sdf.Reference(relative_path, prototype_root)]
        source_spec.instanceable = True

    def _route_runtime(
        self,
        base_layer: Sdf.Layer,
        base_instances_layer: Sdf.Layer,
        reference_map: dict[Sdf.Path, Sdf.Path],
        runtime: dict,
    ) -> bool:
        folder = runtime["folder"]
        enabled_path = os.path.join(self.package_root, "payloads", folder, "enabled.usda")
        if not os.path.isfile(enabled_path):
            self.log_operation(f"Runtime enabled layer not found, skipping {folder}: {enabled_path}")
            return False

        runtime_instances_relative = runtime.get(
            "instances_layer",
            f"payloads/instances_{folder.lower()}.usda",
        )
        runtime_instances_path = os.path.join(self.package_root, runtime_instances_relative)
        os.makedirs(os.path.dirname(runtime_instances_path), exist_ok=True)
        if os.path.exists(runtime_instances_path):
            os.remove(runtime_instances_path)
        if not base_instances_layer.Export(runtime_instances_path):
            raise RuntimeError(f"Could not create runtime instances layer: {runtime_instances_path}")

        enabled_layer = Sdf.Layer.FindOrOpen(enabled_path)
        runtime_instances_layer = Sdf.Layer.FindOrOpen(runtime_instances_path)
        if enabled_layer is None or runtime_instances_layer is None:
            raise RuntimeError(f"Could not open runtime layers for {folder}")

        relocations: list[tuple[Sdf.Path, Sdf.Path, Sdf.Path]] = []
        for root_prim in enabled_layer.rootPrims:
            for prim_spec in list(self._walk_prim_specs(root_prim)):
                if not self._has_runtime_mesh_opinions(prim_spec):
                    continue
                source_root = self._find_source_root(prim_spec.path, reference_map)
                if source_root is None:
                    continue
                prototype_root = reference_map[source_root]
                prototype_mesh = self._prototype_mesh_path(prim_spec.path, source_root, prototype_root)
                self._merge_prim_opinions(
                    enabled_layer,
                    prim_spec,
                    runtime_instances_layer,
                    prototype_mesh,
                )
                relocations.append((prim_spec.path, source_root, prototype_root))

        if not relocations:
            os.remove(runtime_instances_path)
            self.log_operation(f"No instanced runtime mesh opinions found for {folder}")
            return False

        for source_path, source_root, _ in sorted(
            relocations,
            key=lambda item: len(item[0].pathString),
            reverse=True,
        ):
            if source_path != source_root:
                self._remove_prim_spec(enabled_layer, source_path)

        routed_roots: dict[Sdf.Path, Sdf.Path] = {}
        for _, source_root, prototype_root in relocations:
            routed_roots[source_root] = prototype_root
        for source_root, prototype_root in routed_roots.items():
            self._author_runtime_reference(
                enabled_layer,
                source_root,
                runtime_instances_path,
                prototype_root,
            )

        runtime_instances_layer.Save()
        enabled_layer.Save()
        self.add_affected_stage(runtime_instances_path)
        self.add_affected_stage(enabled_path)
        self.log_operation(
            f"Routed {len(relocations)} {folder} mesh opinion set(s) "
            f"through {len(routed_roots)} runtime instance reference(s)"
        )
        return True

    def process_rule(self) -> str | None:
        params = self.args.get("params", {}) or {}
        instances_relative = params.get("instances_layer") or "payloads/instances.usda"
        instances_path = os.path.join(self.package_root, instances_relative)
        base_path = self.source_stage.GetRootLayer().realPath
        base_layer = Sdf.Layer.FindOrOpen(base_path)
        instances_layer = Sdf.Layer.FindOrOpen(instances_path)
        if base_layer is None or instances_layer is None:
            raise RuntimeError("Runtime instance routing requires generated base and instances layers")

        reference_map = self._reference_map(base_layer, os.path.basename(instances_path))
        if not reference_map:
            self.log_operation("No generated instance references found; runtime routing skipped")
            return None

        runtimes = params.get("runtimes") or self.get_configuration_parameters()[1].default_value
        routed_count = 0
        for runtime in runtimes:
            if self._route_runtime(base_layer, instances_layer, reference_map, runtime):
                routed_count += 1
        self.log_operation(f"RuntimeInstanceRoutingRule completed for {routed_count} runtime(s)")
        return None
