[Robot-Body-Isaac]
"1.0.0" = {features = [
    {"FET_001_STANDARD" = {version = "0.1.0"}}, # "Minimal"
    {"FET_004_ROBOT_PHYSX" = {version = "0.2.0"}}, # "Simulate Multi-Body Physics and SDF collision approximation"
    {"FET_021_ISAAC" = {version = "0.2.0"}}, # "Robot Core Isaac"
    {"FET_022_ISAAC" = {version = "0.1.0"}}, # "Isaac Driven Joints
    {"FET_024_PHYSX" = {version = "0.1.0"}}, # "Isaac Base Articulation"
    {"FET_100_ISAAC" = {version = "0.1.0"}}, # "Isaac composition
]}
"1.1.0" = {features = [ # Deprecate RB.006
    {"FET_001_STANDARD" = {version = "0.1.0"}}, # "Minimal"
    {"FET_003_PHYSX" = {version = "0.4.0"}}, # "RBD Physics"
    {"FET_004_PHYSX" = {version = "0.4.0"}}, # "Simulate Multi-Body Physics"
    {"FET_021_ISAAC" = {version = "0.2.0"}}, # "Robot Core Isaac"
    {"FET_022_ISAAC" = {version = "0.2.0"}}, # "Isaac Driven Joints
    {"FET_024_PHYSX" = {version = "0.1.0"}}, # "Isaac Base Articulation"
    {"FET_100_ISAAC" = {version = "0.2.0"}}, # "Isaac composition
]}
"1.2.0" = {features = [ # Deprecate RB.006; adopt robot Isaac composition (FET_101_ISAAC)
    {"FET_001_STANDARD" = {version = "0.1.0"}}, # "Minimal"
    {"FET_003_PHYSX" = {version = "0.4.0"}}, # "RBD Physics"
    {"FET_004_PHYSX" = {version = "0.4.0"}}, # "Simulate Multi-Body Physics"
    {"FET_021_ISAAC" = {version = "0.2.0"}}, # "Robot Core Isaac"
    {"FET_022_ISAAC" = {version = "0.2.0"}}, # "Isaac Driven Joints
    {"FET_024_PHYSX" = {version = "0.1.0"}}, # "Isaac Base Articulation"
    {"FET_101_ISAAC" = {version = "0.1.0"}}, # "Robot Isaac composition
]}
