[project_root]
setting = ".."

[content_root]
name = "sample_content"

[workspace]
subconfigs = []
subconfigs_priority = ["sample_content"]

[validate]
# Validation content is owned by the tiers.
requirements_paths = [
    "nv_core/tiers/simready_foundation_tier_core/simready/foundation/tier_core/capabilities",
]
features_paths = [
    "nv_core/tiers/simready_foundation_tier_core/simready/foundation/tier_core/features",
]
profiles_paths = [
    "nv_core/tiers/simready_foundation_tier_core/simready/foundation/tier_core/profiles",
]

[cip]
adapter_modules_path = "nv_core/cip_specs/asset_handler_modules"
spec_root = "nv_core/sr_specs/docs"

[wrapp]
install_from_server = "omniverse://example.com/simready_content/assets/.wrapp_publish"
publish_to_server = "omniverse://example.com/simready_content/assets/.wrapp_publish"

[prod_backend]
url = "http://example.com:8001"
nv_core_wrapp_repo_url = "omniverse://example.com/simready_foundations/.wrapp_publish"

[action_default_profiles]
add = "Robotics-Prop"
generate = "Robotics-Prop"

[docs]
url = "https://nvidia.github.io/simready-foundation/latest/"
